modLoader = "javafml"
loaderVersion = "[1,)"

license = "UNLICENSED"

[[mods]]
modId = "trimeffects"
version = "${version}"

displayName = "TrimsEffects"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/trimseffects"

authors = "lupiiin_, luavixen <lua@foxgirl.dev> (https://foxgirl.dev/)"
description = "Makes armor trims grant special effects."

logoFile = "assets/trimeffects/icon.png"

[[mixins]]
config = "trimeffects.mixins.json"

[[dependencies.trimeffects]]
modId = "neoforge"
mandatory = true
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trimeffects]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version_min},${minecraft_version_max})"
ordering = "NONE"
side = "BOTH"
